import Head from 'next/head'
//import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react"

const Home = () => {
  const [problems, setProblems] = useState([])

  const fetchproblems = () => {
    fetch("https://codeforces.com/api/user.status?handle=tourist&from=1&count=4000")
      .then(response => {
        return response.json()
      })
      .then(data => {
        setProblems(data.result)
      })
  }

  useEffect(() => {
    fetchproblems()
  }, [])

  problems.filter((problem)=>{
    return problem.verdict !== "OK";
  })



  const [users, setUsers] = useState([])

  const fetchusers = () => {
    fetch("https://codeforces.com/api/user.status?handle=anirudtate&from=1&count=4000")
      .then(response => {
        return response.json()
      })
      .then(data => {
        setUsers(data.result)
      })
  }

  useEffect(() => {
    fetchusers()
  }, [])

  problems.forEach((problem)=>{
    users.forEach((user)=>{
      if(problem.solved === "solved" || problem.problem.contestId === user.problem.contestId && problem.problem.index === user.problem.index){
        problem.solved="solved";
      }
      else{
        problem.solved="unsolved";
      }
    })
  })

  let prob = new Set();
  for(let i=0;i<problems.length;i++){
    if(problems[i].verdict === "OK"){
      let obj = {};
      obj.name = problems[i].problem.name;
      obj.contest = problems[i].problem.contestId;
      obj.sub = problems[i].id;
      obj.solved = problems[i].solved;
      obj.letter = problems[i].problem.index;
      obj.rating = problems[i].problem.rating;
      prob.add(obj);
    }
  }

  const probs = Array.from(prob).sort((a,b) => {
    return a.rating - b.rating;
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Yet Another <a target="_blank" rel="noopener noreferrer" href="https://codeforces.com">Codeforces</a> Ladder
        </h1>
        <p className={styles.description}>
          created by {' '}
          <a target="_blank" rel="noopener noreferrer" href="https://codeforces.com/profile/anirudtate">anirudtate</a>
        </p>

        <div className={styles.grid}>
          {probs.map(problem => (
            <>
            <a className={styles.card} target="_blank" rel="noopener noreferrer" href={"https://codeforces.com/contest/" + problem.contest + "/problem/" + problem.letter}>
              {problem.name}
            </a>
            <div className={styles.card2}>
              {problem.solved}
            </div>
            <a className={styles.card3} target="_blank" rel="noopener noreferrer" href={"https://codeforces.com/contest/" + problem.contest + "/submission/" + problem.sub}>code</a>
            </>
          ))}
        </div>
      </main>
    </div>
  )
}

export default Home;
